### ISSUE TITLE
Aure Iot Central DPS

### ISSUE THREAD

**Issue by jorgevinagre** [olivierbloch/RPiZero-AzureIoT-Python-Demo#1]
Hi Olivier

I was trying to use the IoTCentral script. Where can I find the PROVISIONING_HOST ?

Thanks

**Comment by olivierbloch** [comment]
Hi @SirLancelotDuLac ,
The Provisioning Host is the DPS global device endpoint:
PROVISIONING_HOST=global.azure-devices-provisioning.net
For now IoT Central systematically uses this one, but I prefer keeping it as an env variable as I am working on merging the IoT Hub and IoT Central samples into a single one and when using IoT Hub + DPS directly, you can use the endpoint for your own instance of DPS rather than the global one

**Comment by olivierbloch** [comment]
I just added a comment in the core about this. Closing this issue.
Thanks!
